global:
  nacos:
    server-addr: 39.105.240.237:8848
  datasource:
    service:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://90service:2019/seed?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  redis:
    host: 192.168.51.152
    password: ZGPHdata2019--
    port: 36379
    database: 14
  seed-admin:
    server-name: seed-admin
    port: 2632
  seed-boot-service:
    server-name: seed-boot-service
    port: 2633
    username: admin
    password: admin
    title: "spring-seed"
  seed-api:
    server-name: seed-api
    port: 2634
  seed-auth:
    server-name: seed-auth
    port: 2635